In [22]:
import json

json_file_path = "news.json"

with open('news.json') as file:
    json_lines = file.readlines()

data=[]
for json_line in json_lines:
    json_data = json.loads(json_line)
    data.append(json_data)

In [23]:
import pandas as pd
import pickle
from pandas_profiling import ProfileReport
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [24]:
df= pd.DataFrame(data)

In [25]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import pickle
from pandas_profiling import ProfileReport
import numpy as np
import seaborn as sns

In [26]:
df

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
209522,https://www.huffingtonpost.com/entry/rim-ceo-t...,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,"Reuters, Reuters",2012-01-28
209523,https://www.huffingtonpost.com/entry/maria-sha...,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",,2012-01-28
209524,https://www.huffingtonpost.com/entry/super-bow...,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",,2012-01-28
209525,https://www.huffingtonpost.com/entry/aldon-smi...,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,,2012-01-28
209526,https://www.huffingtonpost.com/entry/dwight-ho...,Dwight Howard Rips Teammates After Magic Loss ...,SPORTS,The five-time all-star center tore into his te...,,2012-01-28

In [27]:
df.describe()

,link,headline,category,short_description,authors,date
count,209527,209527,209527,209527,209527,209527
unique,209486,207996,42,187022,29169,3890
top,https://www.huffingtonpost.comhttps://www.wash...,Sunday Roundup,POLITICS,,,2014-03-25
freq,2,90,35602,19712,37418,100

In [28]:
df[df.duplicated()]

,link,headline,category,short_description,authors,date
67677,https://www.huffingtonpost.comhttp://www.mothe...,"On Facebook, Trump's Longtime Butler Calls For...",POLITICS,"Anthony Senecal, who worked as Donald Trump's ...",,2016-05-12
67923,https://www.huffingtonpost.comhttp://gizmodo.c...,Former Facebook Workers: We Routinely Suppress...,TECH,Facebook workers routinely suppressed news sto...,,2016-05-09
70239,https://www.huffingtonpost.comhttp://www.cnbc....,"On Equal Pay Day, The Gap Is Still Too Wide",WOMEN,Equal Pay Day falls on April 12 in 2016. It's ...,,2016-04-12
139830,https://www.huffingtonpost.comhttp://www.cnn.c...,The World's Most Dangerous Workout?,WELLNESS,"Is the ""sport of fitness"" the world's most dan...",,2014-02-10
144409,https://www.huffingtonpost.comhttp://www.upwor...,Some People Call It 'The Best Anti-Smoking Ad ...,WELLNESS,Almost all smokers know cigarettes are bad for...,,2013-12-22
145142,https://www.huffingtonpost.comhttp://www.weath...,10 Cities That Could Run Out Of Water - Weathe...,ENVIRONMENT,"Securing access to plentiful, renewable source...",,2013-12-15
178155,https://www.huffingtonpost.comhttp://www.busin...,Google Is Attacking Apple From The Inside Out ...,TECH,After years of hammering away at Apple's share...,,2013-01-01
187329,https://www.huffingtonpost.comhttp://www.nytim...,"Eating For Health, Not Weight",WELLNESS,Almost half of Americans are on a diet -- not ...,,2012-09-23
194596,https://www.huffingtonpost.comhttp://blogs.wsj...,Apple Removes Green EPEAT Electronics Certific...,TECH,Apple has pulled its products off the U.S. gov...,,2012-07-07
194598,https://www.huffingtonpost.comhttp://www.theda...,Microsoft's $6.2 Billion Writedown Shows It's ...,TECH,Fighting for online advertising dominance with...,,2012-07-07
207122,https://www.huffingtonpost.comhttp://d.repubbl...,Versace Atelier Worker Reflects On The Glory &...,STYLE & BEAUTY,"Twenty-four hours before the fashion show, Don...",,2012-02-23
207208,https://www.huffingtonpost.comhttp://d.repubbl...,Behind-The-Scenes Look At Prada's Workshop (VI...,STYLE & BEAUTY,Exclusive worldwide and for the first time in ...,,2012-02-22
207318,https://www.huffingtonpost.comhttp://d.repubbl...,Gucci's Frida Giannini Reveals Fashion Week Di...,STYLE & BEAUTY,Frida Giannini reveals in this worldwide exclu...,,2012-02-21

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209527 entries, 0 to 209526
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   link               209527 non-null  object
 1   headline           209527 non-null  object
 2   category           209527 non-null  object
 3   short_description  209527 non-null  object
 4   authors            209527 non-null  object
 5   date               209527 non-null  object
dtypes: object(6)
memory usage: 9.6+ MB

In [30]:
df.shape

(209527, 6)

In [31]:
df['category'].unique()

array(['U.S. NEWS', 'COMEDY', 'PARENTING', 'WORLD NEWS', 'CULTURE & ARTS',
       'TECH', 'SPORTS', 'ENTERTAINMENT', 'POLITICS', 'WEIRD NEWS',
       'ENVIRONMENT', 'EDUCATION', 'CRIME', 'SCIENCE', 'WELLNESS',
       'BUSINESS', 'STYLE & BEAUTY', 'FOOD & DRINK', 'MEDIA',
       'QUEER VOICES', 'HOME & LIVING', 'WOMEN', 'BLACK VOICES', 'TRAVEL',
       'MONEY', 'RELIGION', 'LATINO VOICES', 'IMPACT', 'WEDDINGS',
       'COLLEGE', 'PARENTS', 'ARTS & CULTURE', 'STYLE', 'GREEN', 'TASTE',
       'HEALTHY LIVING', 'THE WORLDPOST', 'GOOD NEWS', 'WORLDPOST',
       'FIFTY', 'ARTS', 'DIVORCE'], dtype=object)

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances, manhattan_distances

In [43]:
x= [entry['headline']+" "+entry['short_description'] for entry in data]

In [34]:
df.isnull().sum()

link                 0
headline             0
category             0
short_description    0
authors              0
date                 0
dtype: int64

In [44]:
vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(x)

In [45]:
tfidf_matrix

<209527x88507 sparse matrix of type '<class 'numpy.float64'>'
	with 5201305 stored elements in Compressed Sparse Row format>

In [46]:
def find_similar_data(data_to_be_given):
    query_vector = vectorizer.transform([query])

    cosine_sim = cosine_similarity(tfidf_matrix, query_vector).flatten()
    euclidean_sim = euclidean_distances(tfidf_matrix, query_vector).flatten()
    manhattan_sim = manhattan_distances(tfidf_matrix, query_vector).flatten()
    
    similarity_scores = (cosine_sim + euclidean_sim + manhattan_sim ) / 4

    top_indices = similarity_scores.argsort()[::-1]

    similar_data = df.iloc[top_indices]

    return similar_data

In [47]:
query ="Over 4 Million Americans Roll Up Sleeves For Omicron-Targeted COVID Boosters"+" "+"Health experts said it is too early to predict whether demand would match up with the 171 million doses of the new boosters the U.S. ordered for the fall."
similar_data = find_similar_data(query)
print(similar_data)

                                                     link  \
109802  https://www.huffingtonpost.com/entry/weekend-r...
63109   https://www.huffingtonpost.com/entry/sunday-ro...
72892   https://www.huffingtonpost.com/entry/sunday-ro...
66816   https://www.huffingtonpost.com/entry/sunday-ro...
107893  https://www.huffingtonpost.com/entry/sunday-ro...
...                                                   ...
110153  https://www.huffingtonpost.com/entry/beverly-h...
109100  https://www.huffingtonpost.com/entry/disney-ce...
90944   https://www.huffingtonpost.com/entry/lincoln-2...
103675  https://www.huffingtonpost.com/entry/us-and-eu...
0       https://www.huffpost.com/entry/covid-boosters-...

                                                 headline   category  \
109802                   Weekend Roundup: Laughing at God  WORLDPOST
63109                                      Sunday Roundup   POLITICS
72892                                      Sunday Roundup   POLITICS
66816                                      Sunday Roundup   POLITICS
107893                                     Sunday Roundup   POLITICS
...                                                   ...        ...
110153                                                         MEDIA
109100                                                      BUSINESS
90944                                                       POLITICS
103675                                                     WORLDPOST
0       Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS

                                        short_description  \
109802  The first principle of an open society is not ...
63109   This week, the nation was reminded, in ways bo...
72892   This week the GOP debate circus pulled into Mi...
66816   This week the nation watched as the #NeverTrum...
107893  This week began with "The Horrible Call" final...
...                                                   ...
110153
109100
90944
103675
0       Health experts said it is too early to predict...

                                                  authors        date
109802  Nathan Gardels, ContributorEditor-in-chief, Th...  2015-01-17
63109                     Arianna Huffington, Contributor  2016-07-03
72892                     Arianna Huffington, Contributor  2016-03-13
66816                     Arianna Huffington, Contributor  2016-05-22
107893                    Arianna Huffington, Contributor  2015-02-08
...                                                   ...         ...
110153  Gary Snyder, ContributorWriter and Media Strat...  2015-01-13
109100  Gary Snyder, ContributorWriter and Media Strat...  2015-01-25
90944   Robert Moran, ContributorRobert Moran leads Br...  2015-08-22
103675  Natasha Srdoc, ContributorAuthor, Economist, C...  2015-03-29
0                                    Carla K. Johnson, AP  2022-09-23

[209527 rows x 6 columns]

In [ ]:
find similar data using headlines and short description combination